/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_proje_ödevi_halilibrahim;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author halil
 */
public class KargoÜcretiHesapla extends javax.swing.JFrame {
JTextField ücrethesabı;
    /**
     * Creates new form KargoÜcretiHesapla
     */
    public KargoÜcretiHesapla() {
        initComponents();
      AlıcıyaMesaj.setVisible(false);
      göndericiyeMesaj.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
       
    } boolean desenKontrol(String desenMetni, String icindeDesenArananMetin) {

        Pattern desen = Pattern.compile(desenMetni);
        Matcher arama = desen.matcher(icindeDesenArananMetin);
        return arama.find();

    }
     public KargoÜcretiHesapla(JTextField j) {
        initComponents();
      AlıcıyaMesaj.setVisible(false);
      göndericiyeMesaj.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
       ücrethesabı=j;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTeslim = new javax.swing.ButtonGroup();
        groupTür = new javax.swing.ButtonGroup();
        btnGüniçi = new javax.swing.JRadioButton();
        NormalKargo = new javax.swing.JRadioButton();
        btnÖncelik = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnAkşam = new javax.swing.JRadioButton();
        en = new javax.swing.JTextField();
        btnStrandart = new javax.swing.JRadioButton();
        boy = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        yükseklik = new javax.swing.JTextField();
        btnAdrestenAl = new javax.swing.JRadioButton();
        agırlık = new javax.swing.JTextField();
        btnMesaj = new javax.swing.JRadioButton();
        ücretiHesapla = new javax.swing.JButton();
        göndericiyeMesaj = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        AlıcıyaMesaj = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        HassasKargo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGüniçi.setText("Güniçi Teslimat");
        btnGüniçi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGüniçiActionPerformed(evt);
            }
        });

        NormalKargo.setText("Normal Gönderi");
        NormalKargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalKargoActionPerformed(evt);
            }
        });

        btnÖncelik.setText("Öncelikli  Teslimat");
        btnÖncelik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnÖncelikActionPerformed(evt);
            }
        });

        jLabel5.setText("Hacim Hesapla");

        btnAkşam.setText("Akşam Teslimat");
        btnAkşam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAkşamActionPerformed(evt);
            }
        });

        en.setText("En");
        en.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enMouseClicked(evt);
            }
        });
        en.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enActionPerformed(evt);
            }
        });
        en.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enKeyTyped(evt);
            }
        });

        btnStrandart.setText("Standart");
        btnStrandart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStrandartActionPerformed(evt);
            }
        });

        boy.setText("Boy");
        boy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boyMouseClicked(evt);
            }
        });
        boy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boyActionPerformed(evt);
            }
        });
        boy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                boyKeyTyped(evt);
            }
        });

        jLabel6.setText("Ek hizmet");

        yükseklik.setText("Yükseklik");
        yükseklik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yükseklikMouseClicked(evt);
            }
        });
        yükseklik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yükseklikActionPerformed(evt);
            }
        });
        yükseklik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                yükseklikKeyTyped(evt);
            }
        });

        btnAdrestenAl.setText("Adresten Alım");
        btnAdrestenAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdrestenAlActionPerformed(evt);
            }
        });

        agırlık.setText("Ağırlık");
        agırlık.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agırlıkMouseClicked(evt);
            }
        });
        agırlık.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agırlıkActionPerformed(evt);
            }
        });
        agırlık.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agırlıkKeyTyped(evt);
            }
        });

        btnMesaj.setText("Mesaj");
        btnMesaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesajActionPerformed(evt);
            }
        });

        ücretiHesapla.setText("Ücreti Hesapla");
        ücretiHesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ücretiHesaplaActionPerformed(evt);
            }
        });

        göndericiyeMesaj.setText("Gödericiye SMS");
        göndericiyeMesaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                göndericiyeMesajActionPerformed(evt);
            }
        });

        jLabel7.setText("Teslim Zamanı");

        AlıcıyaMesaj.setText("Alıcıya SMS");
        AlıcıyaMesaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlıcıyaMesajActionPerformed(evt);
            }
        });

        jLabel4.setText("Gönderi Türü");

        HassasKargo.setText("Hassas Kargo");
        HassasKargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HassasKargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(en, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGüniçi)
                            .addComponent(btnAdrestenAl)
                            .addComponent(HassasKargo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMesaj)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(boy, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnÖncelik))
                                        .addGap(135, 135, 135)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(yükseklik, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAkşam))
                                        .addGap(143, 143, 143)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnStrandart)
                                            .addComponent(agırlık, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(göndericiyeMesaj)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AlıcıyaMesaj))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(NormalKargo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(ücretiHesapla)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HassasKargo)
                    .addComponent(NormalKargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(en, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yükseklik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agırlık, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGüniçi)
                    .addComponent(btnÖncelik)
                    .addComponent(btnAkşam)
                    .addComponent(btnStrandart))
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdrestenAl)
                    .addComponent(btnMesaj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(göndericiyeMesaj)
                    .addComponent(AlıcıyaMesaj))
                .addGap(18, 18, 18)
                .addComponent(ücretiHesapla)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Paket p = new Paket();
    private void btnGüniçiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGüniçiActionPerformed
        btnTeslim.add(btnGüniçi);
        if (btnGüniçi.isSelected()) {
            p.teslimatAralığı=("Kargonuz saat 09.00 ile 14.00 saatleri arasında alıcıya teslim edilecektir.");
            p.kargoÜcreti += 5;
        }
    }//GEN-LAST:event_btnGüniçiActionPerformed

    private void NormalKargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalKargoActionPerformed
        if (NormalKargo.isSelected()) {
            p.kargoÜcreti += 1;
        }
        groupTür.add(NormalKargo);
    }//GEN-LAST:event_NormalKargoActionPerformed

    private void btnÖncelikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnÖncelikActionPerformed
        btnTeslim.add(btnÖncelik);
        if (btnÖncelik.isSelected()) {
            p.kargoÜcreti += 10;
        }
    }//GEN-LAST:event_btnÖncelikActionPerformed

    private void btnAkşamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAkşamActionPerformed
        btnTeslim.add(btnAkşam);
        if (btnAkşam.isSelected()) {
            p.teslimatAralığı=("Kargonuz saat 16.00 ile 18.00 saatleri arasında alıcıya teslim edilecektir.");
            p.kargoÜcreti += 7;
        }
    }//GEN-LAST:event_btnAkşamActionPerformed

    private void enActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enActionPerformed
    p.en= en.getText();
           p.kargoÜcreti+=Float.parseFloat(p.ağırlık)*0.75;
    }//GEN-LAST:event_enActionPerformed

    private void btnStrandartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStrandartActionPerformed
        btnTeslim.add(btnStrandart);
        if (btnStrandart.isSelected()) {
            p.teslimatAralığı=("Kargonuz en kısa sürede alıcıya teslim edilecektir.");
            p.kargoÜcreti = p.kargoÜcreti;
        }
    }//GEN-LAST:event_btnStrandartActionPerformed

    private void boyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boyActionPerformed
        
    }//GEN-LAST:event_boyActionPerformed

    private void yükseklikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yükseklikActionPerformed
       
    }//GEN-LAST:event_yükseklikActionPerformed

    private void agırlıkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agırlıkActionPerformed
        
    }//GEN-LAST:event_agırlıkActionPerformed

    private void btnMesajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesajActionPerformed
        if (btnMesaj.isSelected()) {
            göndericiyeMesaj.setVisible(true);
            AlıcıyaMesaj.setVisible(true);

        }
    }//GEN-LAST:event_btnMesajActionPerformed

    private void ücretiHesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ücretiHesaplaActionPerformed
            
           p.yükseklik=yükseklik.getText();
           p.kargoÜcreti+=Float.parseFloat(yükseklik.getText())*0.75;
          (p.boy)=boy.getText();
           p.kargoÜcreti+=Float.parseFloat(boy.getText())*0.75;
           p.ağırlık=agırlık.getText();
           p.kargoÜcreti+=Float.parseFloat(agırlık.getText())*0.75;
           p.yükseklik=yükseklik.getText();
           p.kargoÜcreti+=Float.parseFloat(yükseklik.getText())*0.75;
           ücrethesabı.setText(String.valueOf(p.kargoÜcreti));
        
        JOptionPane.showMessageDialog(rootPane, p.kargoÜcreti,"Ücret hesaplama",JOptionPane.INFORMATION_MESSAGE);
      
         
    }//GEN-LAST:event_ücretiHesaplaActionPerformed

    private void göndericiyeMesajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_göndericiyeMesajActionPerformed
        if (göndericiyeMesaj.isSelected()) {
            p.kargoÜcreti+=1.50;

        }
    }//GEN-LAST:event_göndericiyeMesajActionPerformed

    private void AlıcıyaMesajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlıcıyaMesajActionPerformed
        AlıcıyaMesaj.isSelected();
        p.kargoÜcreti+=1.50;
    }//GEN-LAST:event_AlıcıyaMesajActionPerformed

    private void HassasKargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HassasKargoActionPerformed
        // TODO add your handling code here:
        if (HassasKargo.isSelected()) {
            p.kargoÜcreti += 5;
        }
        groupTür.add(HassasKargo);
    }//GEN-LAST:event_HassasKargoActionPerformed

    private void btnAdrestenAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdrestenAlActionPerformed
        if (btnAdrestenAl.isSelected()) {
            p.kargoÜcreti+=5;
        }
    }//GEN-LAST:event_btnAdrestenAlActionPerformed

    private void enMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enMouseClicked
        en.setText(null);
    }//GEN-LAST:event_enMouseClicked

    private void boyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boyMouseClicked
        boy.setText(null);
    }//GEN-LAST:event_boyMouseClicked

    private void yükseklikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yükseklikMouseClicked
       yükseklik.setText(null);
    }//GEN-LAST:event_yükseklikMouseClicked

    private void agırlıkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agırlıkMouseClicked
       agırlık.setText(null);
    }//GEN-LAST:event_agırlıkMouseClicked

    private void enKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {

            evt.consume();
        }
    }//GEN-LAST:event_enKeyTyped

    private void boyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boyKeyTyped
       char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {

            evt.consume();
        }
    }//GEN-LAST:event_boyKeyTyped

    private void yükseklikKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yükseklikKeyTyped
      char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {

            evt.consume();
        }
    }//GEN-LAST:event_yükseklikKeyTyped

    private void agırlıkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agırlıkKeyTyped
       char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9'))&& (caracter != '\b')) {

            evt.consume();
        }
        
         
        
    }//GEN-LAST:event_agırlıkKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KargoÜcretiHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KargoÜcretiHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KargoÜcretiHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KargoÜcretiHesapla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KargoÜcretiHesapla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AlıcıyaMesaj;
    private javax.swing.JRadioButton HassasKargo;
    private javax.swing.JRadioButton NormalKargo;
    private javax.swing.JTextField agırlık;
    private javax.swing.JTextField boy;
    private javax.swing.JRadioButton btnAdrestenAl;
    private javax.swing.JRadioButton btnAkşam;
    private javax.swing.JRadioButton btnGüniçi;
    private javax.swing.JRadioButton btnMesaj;
    private javax.swing.JRadioButton btnStrandart;
    private javax.swing.ButtonGroup btnTeslim;
    private javax.swing.JRadioButton btnÖncelik;
    private javax.swing.JTextField en;
    private javax.swing.ButtonGroup groupTür;
    private javax.swing.JCheckBox göndericiyeMesaj;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField yükseklik;
    private javax.swing.JButton ücretiHesapla;
    // End of variables declaration//GEN-END:variables
}
