/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_proje_ödevi_halilibrahim;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static bp2_proje_ödevi_halilibrahim.SubedekiKargolar.dtm1;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.io.StreamCorruptedException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author halil
 */
public class KargoEkle extends javax.swing.JFrame {

    /**
     * Creates new form KuryeÇağır
     */
    public KargoEkle() {
        initComponents();
        DefaultComboBoxModel cbm = new DefaultComboBoxModel();
        cbm.addElement("Alıcı Ödemeli");
        cbm.addElement("Gönderici Ödemeli");
        cmbÖdeme.setModel(cbm);

    }
    Paket p = new Paket();
    Gonderici g = new Gonderici();
    Alıcı a = new Alıcı();

    public KargoEkle(DefaultTableModel d) {

        d = SubedekiKargolar.dtm1;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    ArrayList<Paket> subeyeni;

    KargoEkle(ArrayList<Paket> a) {
        initComponents();
        subeyeni = a;
    }

    boolean desenKontrol(String desenMetni, String icindeDesenArananMetin) {

        Pattern desen = Pattern.compile(desenMetni);
        Matcher arama = desen.matcher(icindeDesenArananMetin);
        return arama.find();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        jLabel13 = new javax.swing.JLabel();
        txtGöndericiAdres = new javax.swing.JTextField();
        paket = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        txtAlıcıAdı = new javax.swing.JTextField();
        dosya = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        btnDevamEt = new javax.swing.JButton();
        koli = new javax.swing.JToggleButton();
        txtGöndericiTelefon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtGöndericiEposta = new javax.swing.JTextField();
        jComboGöndericiİl = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jComboGöndeiciİlçe = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtAlıcıSoyadı = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGöndericiAdı = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGöndericiSoyadı = new javax.swing.JTextField();
        txtAlıcıTelefon1 = new javax.swing.JTextField();
        txtAlıcıAdres = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtAlıcıEposta = new javax.swing.JTextField();
        jComboAlıcıİl = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jComboAlıcı = new javax.swing.JComboBox();
        btnAnaÜcret = new javax.swing.JButton();
        txtUcret = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cmbÖdeme = new javax.swing.JComboBox<>();
        KargoKimlikNo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel13.setText("Alıcı Adı");

        txtGöndericiAdres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGöndericiAdresActionPerformed(evt);
            }
        });

        paket.setText("Paket");
        paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketActionPerformed(evt);
            }
        });

        jLabel10.setText("Adres");

        txtAlıcıAdı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlıcıAdıActionPerformed(evt);
            }
        });

        dosya.setText("Dosya");
        dosya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaActionPerformed(evt);
            }
        });

        jLabel11.setText("İletişim Bilgileri");

        btnDevamEt.setText("Devam Et");
        btnDevamEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevamEtActionPerformed(evt);
            }
        });

        koli.setText("Koli");
        koli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koliActionPerformed(evt);
            }
        });

        txtGöndericiTelefon.setText("Telefon Numarası");
        txtGöndericiTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGöndericiTelefonActionPerformed(evt);
            }
        });
        txtGöndericiTelefon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGöndericiTelefonKeyTyped(evt);
            }
        });

        jLabel8.setText("Gönderici Adres Bilgileri");

        jLabel9.setText("Gönderi Alım Tarihi");

        txtGöndericiEposta.setText("E-Posta Adresi");
        txtGöndericiEposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGöndericiEpostaActionPerformed(evt);
            }
        });
        txtGöndericiEposta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGöndericiEpostaKeyReleased(evt);
            }
        });

        jComboGöndericiİl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "İl Seçiniz", "İstanbul Anadolu", "İstanbul Avrupa" }));
        jComboGöndericiİl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboGöndericiİlİtemStateChanged(evt);
            }
        });
        jComboGöndericiİl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboGöndericiİlMouseClicked(evt);
            }
        });
        jComboGöndericiİl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGöndericiİlActionPerformed(evt);
            }
        });

        jLabel12.setText("Gönderi Bilgileri");

        jComboGöndeiciİlçe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "İlçe Seçiniz" }));
        jComboGöndeiciİlçe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboGöndeiciİlçeMousePressed(evt);
            }
        });

        jLabel1.setText("Alıcı Soyadı");

        txtAlıcıSoyadı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlıcıSoyadıActionPerformed(evt);
            }
        });

        jLabel2.setText("Gönderici Adı");

        txtGöndericiAdı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGöndericiAdıActionPerformed(evt);
            }
        });

        jLabel3.setText("Gönderici Soyadı");

        txtAlıcıTelefon1.setText("Telefon Numarası");
        txtAlıcıTelefon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlıcıTelefon1ActionPerformed(evt);
            }
        });

        txtAlıcıAdres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlıcıAdresActionPerformed(evt);
            }
        });

        jLabel14.setText("Alıcı Adres Bilgileri");

        jLabel15.setText("Adres");

        txtAlıcıEposta.setText("E-Posta Adresi");
        txtAlıcıEposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlıcıEpostaActionPerformed(evt);
            }
        });

        jComboAlıcıİl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "İl Seçiniz", "İstanbul Anadolu", "İstanbul Avrupa" }));
        jComboAlıcıİl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboAlıcıİlİtemStateChanged(evt);
            }
        });
        jComboAlıcıİl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAlıcıİlActionPerformed(evt);
            }
        });

        jLabel16.setText("İletişim Bilgileri");

        jComboAlıcı.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "İlçe Seçiniz" }));
        jComboAlıcı.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboAlıcıMousePressed(evt);
            }
        });
        jComboAlıcı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAlıcıActionPerformed(evt);
            }
        });

        btnAnaÜcret.setText("Ücreti Hesapla");
        btnAnaÜcret.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnaÜcretMouseClicked(evt);
            }
        });
        btnAnaÜcret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnaÜcretActionPerformed(evt);
            }
        });

        txtUcret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUcretActionPerformed(evt);
            }
        });

        jLabel4.setText("Ödeme Tipi");

        cmbÖdeme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alıcı Ödemeli", "Gönderici Ödemeli" }));
        cmbÖdeme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbÖdemeActionPerformed(evt);
            }
        });

        KargoKimlikNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KargoKimlikNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnDevamEt)
                .addGap(0, 753, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(KargoKimlikNo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(paket)
                                        .addGap(18, 18, 18)
                                        .addComponent(dosya)
                                        .addGap(26, 26, 26)
                                        .addComponent(koli)
                                        .addGap(227, 227, 227)
                                        .addComponent(cmbÖdeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(211, 211, 211)
                                                .addComponent(btnAnaÜcret)))
                                        .addGap(32, 32, 32)
                                        .addComponent(txtUcret, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 284, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(388, 388, 388)
                                        .addComponent(jLabel15))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtGöndericiTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtGöndericiEposta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtGöndericiAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jComboGöndericiİl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(106, 106, 106)
                                                .addComponent(jComboGöndeiciİlçe, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAlıcıAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jComboAlıcıİl, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(106, 106, 106)
                                                .addComponent(jComboAlıcı, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtAlıcıTelefon1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(93, 93, 93)
                                                        .addComponent(txtAlıcıEposta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(68, 68, 68))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(245, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(349, 349, 349))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGöndericiAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGöndericiSoyadı, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAlıcıAdı, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAlıcıSoyadı, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 73, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(KargoKimlikNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtGöndericiAdı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtGöndericiSoyadı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlıcıAdı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlıcıSoyadı, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboGöndericiİl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboGöndeiciİlçe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtGöndericiAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtGöndericiTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGöndericiEposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboAlıcıİl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboAlıcı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addComponent(txtAlıcıAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtAlıcıTelefon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAlıcıEposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paket)
                    .addComponent(dosya)
                    .addComponent(koli)
                    .addComponent(cmbÖdeme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAnaÜcret)
                        .addComponent(txtUcret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnDevamEt)
                .addGap(173, 173, 173))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtGöndericiAdresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGöndericiAdresActionPerformed

    }//GEN-LAST:event_txtGöndericiAdresActionPerformed

    private void paketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketActionPerformed
        radioGroup.add(paket);
        if (paket.isSelected()) {
            p.gonderiTipi = "Paket";
        }
    }//GEN-LAST:event_paketActionPerformed

    private void dosyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaActionPerformed
        radioGroup.add(dosya);
        if (dosya.isSelected()) {
            p.gonderiTipi = "Dosya";
        }
    }//GEN-LAST:event_dosyaActionPerformed
    DefaultComboBoxModel<Object> dcm = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Object> dcm1 = new DefaultComboBoxModel<>();
    int kargoKimlikNumarası = 0;
    private void btnDevamEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevamEtActionPerformed
        p.kargoKimlikNumarası++;
        dtm1.addRow(new Object[]{(p.kargoKimlikNumarası), (txtGöndericiAdı.getText()), (p.gonderiTipi), (p.kargoÜcreti), (null)});
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_Proje_Odevi_HalilIbrahimPU");
        EntityManager em = emf.createEntityManager();
        Kargo newKargo = new Kargo();
        newKargo.setKargoid(Integer.parseInt(KargoKimlikNo.getText()));
        newKargo.setAliciadi(txtAlıcıAdı.getText());
        newKargo.setGönderiCiAdi(txtGöndericiAdı.getText());
        newKargo.setGönderitipi(p.gonderiTipi);
        p.kargoÜcreti = (Float.valueOf(txtUcret.getText()));
        newKargo.setTeslimatucreti((int) p.kargoÜcreti);
        newKargo.setÖdemetipi(cmbÖdeme.getSelectedItem().toString());
        newKargo.setAdresiLi(jComboAlıcıİl.getSelectedItem().toString());
        newKargo.setAdresiLçesi(jComboGöndeiciİlçe.getSelectedItem().toString());
        newKargo.setAdres(txtAlıcıAdres.getText());
        newKargo.setTeslimataraliği("teslimataraliği");
        newKargo.setGönderidurumu("Subede");
        newKargo.setTariH(jDateChooser1.getDate().getDate() + "." + jDateChooser1.getDate().getDay() + "." + "2019");
        kargoKimlikNumarası = newKargo.getKargoid();
        em.getTransaction().begin();
        em.persist(newKargo);

       /* ObjectOutputStream oos = null;
        String file = String.valueOf(newKargo.getKargoid()) + ".dat";

        try {
            oos = new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream(file)));

            while (true) {
                oos.writeObject(newKargo);
            }

        } catch (EOFException ex) {

        } catch (FileNotFoundException | StreamCorruptedException ex) {

        } catch (IOException ex) {

        } catch (NullPointerException ex) {

        } finally {
            try {
                oos.close();
            } catch (IOException ex) {
                Logger.getLogger(KargoEkle.class.getName()).log(Level.SEVERE, null, ex);
            }
*/
            em.getTransaction().commit();
            em.close();
            emf.close();

            /*Alıcı.alıcılar.add(a);
        Alıcı a = new Alıcı(txtAlıcıAdı.getText(), txtAlıcıSoyadı.getText(),jComboGöndericiİl.getSelectedItem().toString(),jComboGöndeiciİlçe.getSelectedItem().toString() ,txtAlıcıAdres.getText(), txtAlıcıTelefon1.getText(),txtAlıcıEposta.getText());
        Gonderici g1= new Gonderici(txtGöndericiAdı.getText(), txtGöndericiEposta.getText(), jComboGöndericiİl.getSelectedItem().toString(), jComboGöndeiciİlçe.getSelectedItem().toString(), txtGöndericiAdres.getText(), txtGöndericiTelefon.getText(), txtGöndericiEposta.getText(),txtNot.getText(), p,a);
        
        (g1.a.adres) = txtAlıcıAdres.getText();
        (g1.a.adı) = txtAlıcıAdı.getText();
        (g1.a.ePosta) = txtAlıcıEposta.getText();
        (g1.a.telefon) = txtAlıcıTelefon1.getText();
        (g1.adres) = txtGöndericiAdres.getText();
        (g1.adı) = txtGöndericiAdı.getText();
        (g1.ePosta) = txtGöndericiEposta.getText();
        (g1.soyadı) = txtGöndericiSoyadı.getText();
        (g1.telefon) = txtGöndericiTelefon.getText();
        (p.teslimatAralığı) = txtTarih.getText();
        jComboGöndericiİl.getSelectedItem().equals(g.adresİli);
        KargoEkle KargoEkle = new KargoEkle();
        KargoEkle.setVisible(false);
        g1.p=p;
        g1.p.kargoKimlikNumarası++;
        Alıcı.alıcılar.add(g1.a);
        subeyeni.add(p);*/
        
    }//GEN-LAST:event_btnDevamEtActionPerformed

    private void koliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koliActionPerformed
        radioGroup.add(koli);
        if (koli.isSelected()) {
            p.gonderiTipi = "Koli";
        }
    }//GEN-LAST:event_koliActionPerformed

    private void txtGöndericiTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGöndericiTelefonActionPerformed

    }//GEN-LAST:event_txtGöndericiTelefonActionPerformed

    private void txtGöndericiEpostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGöndericiEpostaActionPerformed

    }//GEN-LAST:event_txtGöndericiEpostaActionPerformed

    private void jComboGöndericiİlİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboGöndericiİlİtemStateChanged

    }//GEN-LAST:event_jComboGöndericiİlİtemStateChanged

    private void jComboGöndericiİlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGöndericiİlActionPerformed

    }//GEN-LAST:event_jComboGöndericiİlActionPerformed

    private void txtAlıcıAdıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlıcıAdıActionPerformed

    }//GEN-LAST:event_txtAlıcıAdıActionPerformed

    private void txtAlıcıTelefon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlıcıTelefon1ActionPerformed

    }//GEN-LAST:event_txtAlıcıTelefon1ActionPerformed

    private void txtAlıcıAdresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlıcıAdresActionPerformed

    }//GEN-LAST:event_txtAlıcıAdresActionPerformed

    private void txtAlıcıEpostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlıcıEpostaActionPerformed

    }//GEN-LAST:event_txtAlıcıEpostaActionPerformed

    private void jComboAlıcıİlİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboAlıcıİlİtemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAlıcıİlİtemStateChanged

    private void jComboAlıcıİlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAlıcıİlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAlıcıİlActionPerformed

    private void txtGöndericiTelefonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGöndericiTelefonKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {

            evt.consume();
        }
    }//GEN-LAST:event_txtGöndericiTelefonKeyTyped

    private void txtGöndericiAdıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGöndericiAdıActionPerformed

    }//GEN-LAST:event_txtGöndericiAdıActionPerformed

    private void txtAlıcıSoyadıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlıcıSoyadıActionPerformed

    }//GEN-LAST:event_txtAlıcıSoyadıActionPerformed

    private void txtGöndericiEpostaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGöndericiEpostaKeyReleased

    }//GEN-LAST:event_txtGöndericiEpostaKeyReleased

    private void jComboGöndericiİlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboGöndericiİlMouseClicked

    }//GEN-LAST:event_jComboGöndericiİlMouseClicked

    private void jComboGöndeiciİlçeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboGöndeiciİlçeMousePressed
        String[] ilçelerdizi = {"Ataşehir", "Beykoz", "Çekmeköy", "Kadıköy", "Kartal", "Maltepe", "Pendik", "Sancaktepe", "Sultanbeyli", "Şile", "Tuzla", "Ümraniye", "Üsküdar"};
        String[] ilçeler2dizi = {"Arnavutköy", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş ", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca ", "Esenler", "Esenyurt", "Eyüp ", "Fatih", "Gaziosmanpaşa", "Güngören", "Kağıthane", "Küçükçekmece", "Sarıyer", "Silivri", "Sultangazi", "Şişli", "Zeytinburnu"};
        DefaultComboBoxModel ilçelermodel1 = new DefaultComboBoxModel(ilçelerdizi);
        DefaultComboBoxModel ilçelermodel2 = new DefaultComboBoxModel(ilçeler2dizi);
        String il;

        il = jComboGöndericiİl.getSelectedItem().toString();
        for (int i = 0; i < 2; i++) {

            if (il.equals("İstanbul Anadolu")) {
                jComboGöndeiciİlçe.setModel(ilçelermodel1);
            }
            break;
        }
        if (il.equals("İstanbul Avrupa")) {
            jComboGöndeiciİlçe.setModel(ilçelermodel2);
        }

    }//GEN-LAST:event_jComboGöndeiciİlçeMousePressed

    private void jComboAlıcıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAlıcıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboAlıcıActionPerformed

    private void jComboAlıcıMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboAlıcıMousePressed
        String[] ilçelerdizi = {"Ataşehir", "Beykoz", "Çekmeköy", "Kadıköy", "Kartal", "Maltepe", "Pendik", "Sancaktepe", "Sultanbeyli", "Şile", "Tuzla", "Ümraniye", "Üsküdar"};
        String[] ilçeler2dizi = {"Arnavutköy", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş ", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca ", "Esenler", "Esenyurt", "Eyüp ", "Fatih", "Gaziosmanpaşa", "Güngören", "Kağıthane", "Küçükçekmece", "Sarıyer", "Silivri", "Sultangazi", "Şişli", "Zeytinburnu"};
        DefaultComboBoxModel ilçelermodel1 = new DefaultComboBoxModel(ilçelerdizi);
        DefaultComboBoxModel ilçelermodel2 = new DefaultComboBoxModel(ilçeler2dizi);
        String il;

        il = jComboAlıcıİl.getSelectedItem().toString();
        for (int i = 0; i < 2; i++) {

            if (il.equals("İstanbul Anadolu")) {
                jComboAlıcı.setModel(ilçelermodel1);
            }
            break;
        }
        if (il.equals("İstanbul Avrupa")) {
            jComboAlıcı.setModel(ilçelermodel2);
        }
    }//GEN-LAST:event_jComboAlıcıMousePressed

    private void btnAnaÜcretMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnaÜcretMouseClicked

    }//GEN-LAST:event_btnAnaÜcretMouseClicked

    private void btnAnaÜcretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnaÜcretActionPerformed
        KargoÜcretiHesapla KargoÜcretiHesapla = new KargoÜcretiHesapla(txtUcret);
        KargoÜcretiHesapla.setVisible(true);
    }//GEN-LAST:event_btnAnaÜcretActionPerformed

    private void txtUcretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUcretActionPerformed
        txtUcret.setText(String.valueOf(p.kargoÜcreti));
    }//GEN-LAST:event_txtUcretActionPerformed

    private void cmbÖdemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbÖdemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbÖdemeActionPerformed

    private void KargoKimlikNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KargoKimlikNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KargoKimlikNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KargoEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KargoEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KargoEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KargoEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KargoEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KargoKimlikNo;
    private javax.swing.JButton btnAnaÜcret;
    private javax.swing.JButton btnDevamEt;
    private javax.swing.JComboBox<String> cmbÖdeme;
    private javax.swing.JToggleButton dosya;
    private javax.swing.JComboBox jComboAlıcı;
    private javax.swing.JComboBox jComboAlıcıİl;
    private javax.swing.JComboBox jComboGöndeiciİlçe;
    private javax.swing.JComboBox jComboGöndericiİl;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton koli;
    private javax.swing.JToggleButton paket;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JTextField txtAlıcıAdres;
    private javax.swing.JTextField txtAlıcıAdı;
    private javax.swing.JTextField txtAlıcıEposta;
    private javax.swing.JTextField txtAlıcıSoyadı;
    private javax.swing.JTextField txtAlıcıTelefon1;
    private javax.swing.JTextField txtGöndericiAdres;
    private javax.swing.JTextField txtGöndericiAdı;
    private javax.swing.JTextField txtGöndericiEposta;
    private javax.swing.JTextField txtGöndericiSoyadı;
    private javax.swing.JTextField txtGöndericiTelefon;
    private javax.swing.JTextField txtUcret;
    // End of variables declaration//GEN-END:variables
}
