/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_proje_ödevi_halilibrahim;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author halil
 */
public class KuryeCagir extends javax.swing.JFrame {

    /**
     * Creates new form KuryeCagir
     */
    Paket p = new Paket();
    Boolean b;
    public KuryeCagir() {
        initComponents();
  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        txtEposta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        paket = new javax.swing.JToggleButton();
        txtAd = new javax.swing.JTextField();
        dosya = new javax.swing.JToggleButton();
        koli = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboAlıcıİl = new javax.swing.JComboBox();
        jComboalıcıİlçe = new javax.swing.JComboBox();
        txtAdres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        txtSoyad = new javax.swing.JTextField();
        txtGönderiCiId = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTelefon.setText("Telefon Numarası");
        txtTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 121, -1));

        txtEposta.setText("E-Posta Adresi");
        txtEposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEpostaActionPerformed(evt);
            }
        });
        getContentPane().add(txtEposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 114, -1));

        jLabel6.setText("Gönderi Bilgileri");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 100, 25));

        jLabel2.setText("Alıcı Bilgileri");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 100, 25));

        paket.setText("Paket");
        paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketActionPerformed(evt);
            }
        });
        getContentPane().add(paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        txtAd.setText("Ad");
        getContentPane().add(txtAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 109, -1));

        dosya.setText("Dosya");
        dosya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaActionPerformed(evt);
            }
        });
        getContentPane().add(dosya, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        koli.setText("Koli");
        koli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koliActionPerformed(evt);
            }
        });
        getContentPane().add(koli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, -1));

        jLabel3.setText("Adres Bilgileri");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 100, 25));

        jLabel7.setText("Gönderiniz Ne Zaman Alınsın ?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 186, 25));

        jComboAlıcıİl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "İl Seçiniz", "İstanbul Anadolu", "İstanbul Avrupa" }));
        jComboAlıcıİl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboAlıcıİlİtemStateChanged(evt);
            }
        });
        jComboAlıcıİl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboAlıcıİlActionPerformed(evt);
            }
        });
        getContentPane().add(jComboAlıcıİl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 111, -1));

        jComboalıcıİlçe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "İlçe Seçiniz" }));
        jComboalıcıİlçe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboalıcıİlçeMousePressed(evt);
            }
        });
        jComboalıcıİlçe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboalıcıİlçeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboalıcıİlçe, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 119, -1));

        txtAdres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdresActionPerformed(evt);
            }
        });
        getContentPane().add(txtAdres, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 330, 74));

        jLabel4.setText("Adres");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel5.setText("İletişim Bilgileri");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 100, 25));

        jButton1.setText("Kurye Çağır");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 580, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 186, -1));

        txtSoyad.setText("Soyad");
        getContentPane().add(txtSoyad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 110, -1));

        txtGönderiCiId.setText("txtGönderiCiId");
        getContentPane().add(txtGönderiCiId, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonActionPerformed
 
    }//GEN-LAST:event_txtTelefonActionPerformed

    private void txtEpostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEpostaActionPerformed
      
    }//GEN-LAST:event_txtEpostaActionPerformed

    private void paketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketActionPerformed
        buttonGroup1.add(paket);
        if (paket.isSelected()) {
            p.gonderiTipi = "Paket";
        }
    }//GEN-LAST:event_paketActionPerformed

    private void dosyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaActionPerformed
        buttonGroup1.add(dosya);
        if (dosya.isSelected()) {
            p.gonderiTipi = "Dosya";
        }
    }//GEN-LAST:event_dosyaActionPerformed

    private void koliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koliActionPerformed
        buttonGroup1.add(koli);
          if (koli.isSelected()) {
            p.gonderiTipi = "Koli";
        }
    }//GEN-LAST:event_koliActionPerformed

    private void jComboAlıcıİlİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboAlıcıİlİtemStateChanged

    }//GEN-LAST:event_jComboAlıcıİlİtemStateChanged

    private void jComboAlıcıİlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboAlıcıİlActionPerformed
       

    }//GEN-LAST:event_jComboAlıcıİlActionPerformed
 Gonderici g = new Gonderici();
    private void txtAdresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdresActionPerformed
       
    }//GEN-LAST:event_txtAdresActionPerformed
        int id =6;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_Proje_Odevi_HalilIbrahimPU");
     EntityManager em = emf.createEntityManager();
     Kurye newKurye = new Kurye();
     newKurye.setPaketId(String.valueOf(id));
     newKurye.setAliciad(txtAd.getText());
     newKurye.setAliciadres(txtAdres.getText());
     newKurye.setAlicieposta(txtEposta.getText());
     newKurye.setAliciiL(jComboAlıcıİl.getSelectedItem().toString());
     newKurye.setAliciiLçe(jComboalıcıİlçe.getSelectedItem().toString());
     newKurye.setAlicisoyad(txtSoyad.getText());
     newKurye.setAlicitelefon(txtTelefon.getText());
     newKurye.setGönderiCiId(txtGönderiCiId.getText());
     newKurye.setPakettiPi(p.gonderiTipi);
     newKurye.setTariH(jDateChooser1.getDate().getDate()+"."+jDateChooser1.getDate().getDay()+"."+"2019");
     newKurye.setKargodurum("kuryede");
     em.getTransaction().begin();
     em.persist(newKurye);
     em.getTransaction().commit();
     String a=null;
  
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboalıcıİlçeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboalıcıİlçeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboalıcıİlçeActionPerformed
    
    private void jComboalıcıİlçeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboalıcıİlçeMousePressed
                String[] ilçelerdizi = {"Ataşehir", "Beykoz", "Çekmeköy", "Kadıköy", "Kartal", "Maltepe", "Pendik", "Sancaktepe", "Sultanbeyli", "Şile", "Tuzla", "Ümraniye", "Üsküdar"};
        String[] ilçeler2dizi = {"Arnavutköy", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş ", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca ", "Esenler", "Esenyurt", "Eyüp ", "Fatih", "Gaziosmanpaşa", "Güngören", "Kağıthane", "Küçükçekmece", "Sarıyer", "Silivri", "Sultangazi", "Şişli", "Zeytinburnu"};
        DefaultComboBoxModel ilçelermodel1 = new DefaultComboBoxModel(ilçelerdizi);
        DefaultComboBoxModel ilçelermodel2 = new DefaultComboBoxModel(ilçeler2dizi);
        String il;
        
        il = jComboAlıcıİl.getSelectedItem().toString();
        for (int i = 0; i < 2; i++) {
            
            if (il.equals("İstanbul Anadolu")) {
                jComboalıcıİlçe.setModel(ilçelermodel1);
            }break;
        }
        if (il.equals("İstanbul Avrupa")) {
          jComboalıcıİlçe .setModel(ilçelermodel2);
        }
    }//GEN-LAST:event_jComboalıcıİlçeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KuryeCagir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KuryeCagir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KuryeCagir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KuryeCagir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KuryeCagir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JToggleButton dosya;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboAlıcıİl;
    private javax.swing.JComboBox jComboalıcıİlçe;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton koli;
    private javax.swing.JToggleButton paket;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtAdres;
    private javax.swing.JTextField txtEposta;
    private javax.swing.JTextField txtGönderiCiId;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
