/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_proje_ödevi_halilibrahim;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author halil
 */
public class SubedekiKargolar extends javax.swing.JFrame {

    /**
     * Creates new form SubedekiKargolar
     */
    static DefaultTableModel dtm1 = new DefaultTableModel();
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_Proje_Odevi_HalilIbrahimPU");
    EntityManager em = emf.createEntityManager();
    List<Kargo> kargolar;

    public SubedekiKargolar() {
        initComponents();
        jTable1.setModel(dtm1);
        dtm1.setColumnIdentifiers(new String[]{"Kargo Kimlik NO", "Gönderici Adı","Alıcı Adı" ,"Gönderi Tipi", "Gönderi Ücreti","Gönderici ID " ,"Gönderi Durumu", "Gönderi ilçesi", "Gönderi İli", "Gönderi Tarihi"});
        Query q = em.createQuery("select k from Kargo k ");
        kargolar = q.getResultList();

        for (Kargo k : kargolar) {

            dtm1.addRow(new Object[]{k.getKargoid(), k.getGönderiCiAdi(), k.getAliciadi(), k.getGönderitipi(), k.getTeslimatucreti(),k.getGönderiCiId(), k.getGönderidurumu(), k.getAdresiLçesi(), k.getAdresiLi(), k.getTeslimataraliği()});

        }

    }
    ArrayList<Paket> subedekiPaketleryeni;

    public SubedekiKargolar(ArrayList<Paket> a) {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnGönderiTipineGöreSorgula = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jComboİl = new javax.swing.JComboBox<>();
        jComboİlçe = new javax.swing.JComboBox<>();
        btnSil = new javax.swing.JButton();
        btnİlçeyegöreSorgula = new javax.swing.JButton();
        btnMüsteriYaz = new javax.swing.JButton();
        btnMüsteriOku = new javax.swing.JButton();
        btnKargoYaz = new javax.swing.JButton();
        btnKargoOku = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        btnSubede = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 890, 250));

        btnGönderiTipineGöreSorgula.setText("Gönderi Tipine Göre Sorgula");
        btnGönderiTipineGöreSorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGönderiTipineGöreSorgulaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGönderiTipineGöreSorgula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 200, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Dosya", "Koli", "Paket" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 126, 159));

        jComboİl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İstanbul Anadolu", "İstanbul Avrupa" }));
        getContentPane().add(jComboİl, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        jComboİlçe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboİlçeMousePressed(evt);
            }
        });
        getContentPane().add(jComboİlçe, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 120, -1));

        btnSil.setText("Kargo Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });
        getContentPane().add(btnSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 120, -1));

        btnİlçeyegöreSorgula.setText("İlçeye göre sorgula");
        btnİlçeyegöreSorgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnİlçeyegöreSorgulaActionPerformed(evt);
            }
        });
        getContentPane().add(btnİlçeyegöreSorgula, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, -1, -1));

        btnMüsteriYaz.setText("Dosyaya Yaz");
        btnMüsteriYaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMüsteriYazActionPerformed(evt);
            }
        });
        getContentPane().add(btnMüsteriYaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, 30));

        btnMüsteriOku.setText("Dosyadan oku");
        btnMüsteriOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMüsteriOkuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMüsteriOku, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 120, 30));

        btnKargoYaz.setText("Dosyaya Yaz");
        btnKargoYaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKargoYazActionPerformed(evt);
            }
        });
        getContentPane().add(btnKargoYaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        btnKargoOku.setText("Dosyadan oku");
        btnKargoOku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKargoOkuActionPerformed(evt);
            }
        });
        getContentPane().add(btnKargoOku, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 120, 30));

        jLabel1.setText("Kargo bilgilerini");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jLabel2.setText("Müşteri bilgilerini");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 290, 70));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 290, 70));

        btnSubede.setText("Şubedeki Kargoları Görüntüle");
        btnSubede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubedeActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubede, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 140, -1, 20));

        jButton1.setText("Tüm Kargoları Görüntüle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 200, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnGönderiTipineGöreSorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGönderiTipineGöreSorgulaActionPerformed
        Kargo newKargo = new Kargo();
        dtm1.setRowCount(0);
        Query q = em.createQuery("SELECT k from Kargo k Where k.gönderitipi=:ktip");
        q.setParameter("ktip", jList1.getSelectedValue());
        for (Kargo k : kargolar) {
            if (k.getGönderitipi().equals(jList1.getSelectedValue())) {
                dtm1.addRow(new Object[]{k.getKargoid(), k.getGönderiCiAdi(), k.getAliciadi(), k.getGönderitipi(), k.getTeslimatucreti(), k.getGönderidurumu(), k.getAdresiLçesi(), k.getAdresiLi(), k.getTeslimataraliği()});
            }
        }


    }//GEN-LAST:event_btnGönderiTipineGöreSorgulaActionPerformed

    private void jComboİlçeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboİlçeMousePressed
        String[] ilçelerdizi = {"Ataşehir", "Beykoz", "Çekmeköy", "Kadıköy", "Kartal", "Maltepe", "Pendik", "Sancaktepe", "Sultanbeyli", "Şile", "Tuzla", "Ümraniye", "Üsküdar"};
        String[] ilçeler2dizi = {"Arnavutköy", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş ", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca ", "Esenler", "Esenyurt", "Eyüp ", "Fatih", "Gaziosmanpaşa", "Güngören", "Kağıthane", "Küçükçekmece", "Sarıyer", "Silivri", "Sultangazi", "Şişli", "Zeytinburnu"};
        DefaultComboBoxModel ilçelermodel1 = new DefaultComboBoxModel(ilçelerdizi);
        DefaultComboBoxModel ilçelermodel2 = new DefaultComboBoxModel(ilçeler2dizi);
        String il;

        il = jComboİl.getSelectedItem().toString();
        for (int i = 0; i < 2; i++) {

            if (il.equals("İstanbul Anadolu")) {
                jComboİlçe.setModel(ilçelermodel1);
            }
            break;
        }
        if (il.equals("İstanbul Avrupa")) {
            jComboİlçe.setModel(ilçelermodel2);
        }
    }//GEN-LAST:event_jComboİlçeMousePressed
    Kargo k = new Kargo();
    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
int rowİndex = jTable1.getSelectedRow();
        Query q = em.createQuery("DELETE from Kargo k Where k.kargoid=:id");
        q.setParameter("id", jTable1.getValueAt(jTable1.getSelectedRow(), 0));

        if (jTable1.getValueAt(rowİndex, 5).equals("Araca teslim edildi")) {
            JOptionPane.showMessageDialog(rootPane, "Araca yüklenmiş olan kargolar silinemez", "Uyarı", JOptionPane.WARNING_MESSAGE);

        } else {
            em.getTransaction().begin();;
            q.executeUpdate();
            em.getTransaction().commit();
        }


    }//GEN-LAST:event_btnSilActionPerformed

    private void btnİlçeyegöreSorgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnİlçeyegöreSorgulaActionPerformed
        Kargo newKargo = new Kargo();
        dtm1.setRowCount(0);
        Query q = em.createQuery("SELECT k from Kargo k Where k.adresiLçesi=:kilçe");
        q.setParameter("kilçe", jComboİlçe.getSelectedItem());
        for (Kargo k : kargolar) {
            if ((k.getAdresiLçesi()).equals(jComboİlçe.getSelectedItem())) {
                dtm1.addRow(new Object[]{k.getKargoid(), k.getGönderiCiAdi(), k.getAliciadi(), k.getGönderitipi(), k.getTeslimatucreti(), k.getGönderidurumu(), k.getAdresiLçesi(), k.getAdresiLi(), k.getTeslimataraliği()});
            }
        }
    }//GEN-LAST:event_btnİlçeyegöreSorgulaActionPerformed

    private void btnMüsteriYazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMüsteriYazActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/KargoTakip", "sa", "as");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM MÜSTERİ ");
            while (rs.next()) {
                int id = rs.getInt("M_ID");
                String adı = rs.getString("M_ADI");
                String soyadı = rs.getString("M_SOYADI");
                String ilçe = rs.getString("ADRESİLÇE");
                String eposta = rs.getString("EPOSTA");
                BufferedWriter output = new BufferedWriter(new FileWriter(id + " " + adı + ".txt"));
                output.write(id + " " + adı + " " + soyadı + " " + ilçe + " " + eposta);
                output.close();

            }
            JOptionPane.showMessageDialog(rootPane, "Bilgiler dosyaya aktarıldı", "Bilgi", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(SubedekiKargolar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SubedekiKargolar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMüsteriYazActionPerformed

    private void btnMüsteriOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMüsteriOkuActionPerformed
int rowİndex = jTable1.getSelectedRow();
        if (rowİndex < 0) {
            JOptionPane.showMessageDialog(rootPane, "Sorgulamak için lütfen tablodan kargo seçiniz", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;

        }
        int id = ((int) jTable1.getValueAt(rowİndex, 5));
        String tipi = (String) jTable1.getValueAt(rowİndex, 3);

        try {
            BufferedReader input = new BufferedReader(new FileReader(id + " " + tipi + ".txt"));
            String[] values = input.readLine().split(" ");
            for (String value : values) {
                jTextArea1.setText(values[0]+" "+values[1] +" "+values[2]+" "+values[3]+" "+values[4]);
                
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SubedekiKargolar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SubedekiKargolar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMüsteriOkuActionPerformed

    private void btnKargoOkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKargoOkuActionPerformed
        int rowİndex = jTable1.getSelectedRow();
        if (rowİndex < 0) {
            JOptionPane.showMessageDialog(rootPane, "Sorgulamak için lütfen tablodan kargo seçiniz", "Uyarı", JOptionPane.WARNING_MESSAGE);
            return;

        }
        int id = ((int) jTable1.getValueAt(rowİndex, 0));
        String tipi = (String) jTable1.getValueAt(rowİndex, 3);

        try {
            BufferedReader input = new BufferedReader(new FileReader(id + " " + tipi + ".txt"));
            String[] values = input.readLine().split(" ");
            for (String value : values) {
                jTextArea1.setText(values[0]+" "+values[1] +" "+values[2]+" "+values[3]+" "+values[4]);
                
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SubedekiKargolar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SubedekiKargolar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnKargoOkuActionPerformed

    private void btnSubedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubedeActionPerformed
        dtm1.setRowCount(0);
        Query q = em.createQuery("select k from Kargo k Where k.gönderidurumu=:kid");
        q.setParameter("kid", "Subede");
        kargolar = q.getResultList();

        for (Kargo k : kargolar) {

            dtm1.addRow(new Object[]{k.getKargoid(), k.getGönderiCiAdi(), k.getAliciadi(), k.getGönderitipi(), k.getTeslimatucreti(), k.getGönderidurumu(), k.getAdresiLçesi(), k.getAdresiLi(), k.getTeslimataraliği()});

        }
    }//GEN-LAST:event_btnSubedeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dtm1.setRowCount(0);
        Query q = em.createQuery("select k from Kargo k ");
        kargolar = q.getResultList();

        for (Kargo k : kargolar) {

            dtm1.addRow(new Object[]{k.getKargoid(), k.getGönderiCiAdi(), k.getAliciadi(), k.getGönderitipi(), k.getTeslimatucreti(), k.getGönderidurumu(), k.getAdresiLçesi(), k.getAdresiLi(), k.getTeslimataraliği()});

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnKargoYazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKargoYazActionPerformed
        Query q = em.createQuery("select k from Kargo k Where k.kargoid=:kid");
        q.setParameter("kid", jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        List<Kargo> kargolar = q.getResultList();
        for (Kargo k : kargolar) {
            BufferedWriter output;
            try {
                output = new BufferedWriter(new FileWriter(k.getKargoid() + " " + k.getGönderitipi() + ".txt"));
                output.write(k.getKargoid() + " " + k.getAliciadi() + " " + k.getAdresiLi() + " " + k.getAdresiLçesi() + " " + k.getTeslimatucreti());
                output.close();
                JOptionPane.showMessageDialog(rootPane, "Bilgiler dosyaya aktarıldı", "Bilgi", JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException ex) {
                Logger.getLogger(SubedekiKargolar.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnKargoYazActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubedekiKargolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubedekiKargolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubedekiKargolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubedekiKargolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubedekiKargolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGönderiTipineGöreSorgula;
    private javax.swing.JButton btnKargoOku;
    private javax.swing.JButton btnKargoYaz;
    private javax.swing.JButton btnMüsteriOku;
    private javax.swing.JButton btnMüsteriYaz;
    private javax.swing.JButton btnSil;
    private javax.swing.JButton btnSubede;
    private javax.swing.JButton btnİlçeyegöreSorgula;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboİl;
    private javax.swing.JComboBox<String> jComboİlçe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables

    public JTable getjTable1() {
        return jTable1;
    }

}
