/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_proje_ödevi_halilibrahim;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author halil
 */
public class BireyselDegistir extends javax.swing.JFrame {

    Gonderici gonderici;
    JFrame j;

    /**
     * Creates new form BireyselDegistir
     */
    public BireyselDegistir() {
        initComponents();

    }

    public BireyselDegistir(Gonderici gonderici, JFrame frame) {
        initComponents();
        this.gonderici = gonderici;
        this.j = frame;
    }

    void gelenlerVeriler(String adres, String eposta, String telefon, String adresil, String adresilçe) {

        txtPosta.setText(eposta);
        txttel.setText(telefon);
        lbil.setText(adresil);
        lbilçe.setText(adresilçe);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPosta = new javax.swing.JTextField();
        ADRES = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lbAdres = new javax.swing.JLabel();
        lbTel = new javax.swing.JLabel();
        jComboİl = new javax.swing.JComboBox<>();
        jComboİlçe = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lbPosta = new javax.swing.JLabel();
        lbil = new javax.swing.JLabel();
        lbilçe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbSifre = new javax.swing.JLabel();
        txtSifre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtPosta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 176, -1));

        ADRES.setText("E-POSTA");
        getContentPane().add(ADRES, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel4.setText("TELEFON");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 60, 20));

        jLabel6.setText("ADRES");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 40, 30));
        getContentPane().add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 188, -1));

        jButton1.setText("Onayla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 82, -1));

        lbAdres.setText("jLabel7");
        getContentPane().add(lbAdres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 50, 30));

        lbTel.setText("jLabel8");
        getContentPane().add(lbTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jComboİl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İstanbul Anadolu", "İstanbul Avrupa" }));
        getContentPane().add(jComboİl, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, 30));

        jComboİlçe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboİlçe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboİlçeMousePressed(evt);
            }
        });
        jComboİlçe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboİlçeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboİlçe, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 110, 30));

        jLabel9.setText("Adres il / ilçe");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 104, 40));

        lbPosta.setText("jLabel10");
        getContentPane().add(lbPosta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 106, -1));

        lbil.setText("jLabel3");
        getContentPane().add(lbil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 120, 30));

        lbilçe.setText("jLabel5");
        getContentPane().add(lbilçe, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 100, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 176, 54));

        jLabel1.setText("Bilgilerinizi Görüntülemek için lütfen müşteri ID numaranızı giriniz");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 400, -1));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 80, -1));

        jButton2.setText("Görüntüle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jLabel2.setText("ŞİFRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        lbSifre.setText("jLabel3");
        getContentPane().add(lbSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 306, 70, 20));
        getContentPane().add(txtSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 170, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   ;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_Proje_Odevi_HalilIbrahimPU");
        EntityManager em = emf.createEntityManager();
        Müsteri newMüsteri = new Müsteri();

        Query q;
        q = em.createQuery("UPDATE Müsteri m SET m.adresiL=:il,m.adresiLçe=:ilçe,m.adres=:adres,m.eposta=:eposta,m.mTelefon=:telefon,m.mSiFre=:msifre WHERE m.mId=:id ");
        q.setParameter("id", Integer.parseInt(txtID.getText()));
        q.setParameter("il", jComboİl.getSelectedItem().toString());
        q.setParameter("ilçe", jComboİlçe.getSelectedItem().toString());
        q.setParameter("adres", jTextArea1.getText());
        q.setParameter("eposta", txtPosta.getText());
        q.setParameter("telefon", Integer.parseInt(txttel.getText()));
        q.setParameter("msifre", txtSifre.getText());

        em.getTransaction().begin();
        q.executeUpdate();
        em.getTransaction().commit();
        em.close();

        /*
          ((BireyselAnasayfa)j).getAdres().setText(txtAdres.getText());
            ((BireyselAnasayfa)j).getTel().setText(txttel.getText());
             ((BireyselAnasayfa)j).getEposta().setText(txtPosta.getText());
         */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboİlçeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboİlçeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboİlçeActionPerformed

    private void jComboİlçeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboİlçeMousePressed
      String[] ilçelerdizi = {"Ataşehir", "Beykoz", "Çekmeköy", "Kadıköy", "Kartal", "Maltepe", "Pendik", "Sancaktepe", "Sultanbeyli", "Şile", "Tuzla", "Ümraniye", "Üsküdar"};
        String[] ilçeler2dizi = {"Arnavutköy", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş ", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca ", "Esenler", "Esenyurt", "Eyüp ", "Fatih", "Gaziosmanpaşa", "Güngören", "Kağıthane", "Küçükçekmece", "Sarıyer", "Silivri", "Sultangazi", "Şişli", "Zeytinburnu"};
        DefaultComboBoxModel ilçelermodel1 = new DefaultComboBoxModel(ilçelerdizi);
        DefaultComboBoxModel ilçelermodel2 = new DefaultComboBoxModel(ilçeler2dizi);
        String il;
        
        il = jComboİl.getSelectedItem().toString();
        for (int i = 0; i < 2; i++) {
            
            if (il.equals("İstanbul Anadolu")) {
                jComboİlçe.setModel(ilçelermodel1);
            }break;
        }
        if (il.equals("İstanbul Avrupa")) {
          jComboİlçe .setModel(ilçelermodel2);
        }
    }//GEN-LAST:event_jComboİlçeMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_Proje_Odevi_HalilIbrahimPU");
        EntityManager em = emf.createEntityManager();
       Query q =  em.createQuery("select m from Müsteri m Where m.mId=:mid");
        q.setParameter("mid", Integer.parseInt(txtID.getText()));
        List<Müsteri> müsteriler=q.getResultList();
        for (Müsteri m : müsteriler) {
            lbAdres.setText(m.getAdres());
            lbPosta.setText(m.getEposta());
            lbTel.setText(String.valueOf(m.getMTelefon()));
            lbil.setText(m.getAdresiL());
            lbilçe.setText(m.getAdresiLçe());
            lbSifre.setText(m.getMSiFre());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BireyselDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BireyselDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BireyselDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BireyselDegistir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BireyselDegistir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADRES;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboİl;
    private javax.swing.JComboBox<String> jComboİlçe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbAdres;
    private javax.swing.JLabel lbPosta;
    private javax.swing.JLabel lbSifre;
    private javax.swing.JLabel lbTel;
    private javax.swing.JLabel lbil;
    private javax.swing.JLabel lbilçe;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPosta;
    private javax.swing.JTextField txtSifre;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
