/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_proje_ödevi_halilibrahim;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;

import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author halil
 */
public class Kaydol extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Kaydol() {
        initComponents();
        lb1Email.setVisible(false);
        lbUyarı.setVisible(false);
        lbSifre.setVisible(false);
        jLabel2.setVisible(false);
        jLabel4.setVisible(false);
        jLabel13.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    }
    JOptionPane optionPane;
 void eposta(String eposta){
      try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/KargoTakip", "sa", "as");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM MÜSTERİ ");

            while (rs.next()) {
                if (eposta.equals(rs.getString(6))) {
                     JOptionPane.showMessageDialog(rootPane, "Bu e posta adresi sisteme kayıtlıdır. Lütfen farklı bir e posta adresi giriniz", "Uyarı", JOptionPane.WARNING_MESSAGE);
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(BireyselGiriş.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    boolean desenKontrol(String desenMetni, String icindeDesenArananMetin) {

        Pattern desen = Pattern.compile(desenMetni);
        Matcher arama = desen.matcher(icindeDesenArananMetin);
        return arama.find();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        txtŞifre = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        txtŞifTek = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        txtAdi = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnKaydol = new javax.swing.JButton();
        txtSoyadı = new javax.swing.JTextField();
        txtTekrar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lb1Email = new javax.swing.JLabel();
        lbUyarı = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbSifre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboMüsteriİl = new javax.swing.JComboBox<>();
        jComboMüsteri = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setText("*");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, 20));

        txtŞifre.setText("asdasdsad");
        txtŞifre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtŞifreMouseClicked(evt);
            }
        });
        getContentPane().add(txtŞifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 209, 30));

        jLabel12.setText("Şifre Tekrar");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 20));

        txtŞifTek.setText("adhabshjb");
        txtŞifTek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtŞifTekMouseClicked(evt);
            }
        });
        txtŞifTek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtŞifTekActionPerformed(evt);
            }
        });
        getContentPane().add(txtŞifTek, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 209, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel11.setText("' * ' ile işaretlenmiş alanlar zorunludur.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 60, 381, 16));

        txtAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdiActionPerformed(evt);
            }
        });
        txtAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdiKeyTyped(evt);
            }
        });
        getContentPane().add(txtAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 95, 221, -1));

        txtTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonActionPerformed(evt);
            }
        });
        txtTelefon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 186, 222, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Üyelik Bilgilerinizi Giriniz");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 25, -1, 28));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 234, 221, -1));

        btnKaydol.setText("Kaydol");
        btnKaydol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydolActionPerformed(evt);
            }
        });
        getContentPane().add(btnKaydol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        txtSoyadı.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSoyadıKeyTyped(evt);
            }
        });
        getContentPane().add(txtSoyadı, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 140, 221, -1));

        txtTekrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTekrarActionPerformed(evt);
            }
        });
        getContentPane().add(txtTekrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 186, 20));

        jLabel3.setText("Adınız");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 98, -1, -1));

        lb1Email.setText("Geçerli E-Posta giriniz.");
        getContentPane().add(lb1Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 146, 24));

        lbUyarı.setText("E-Postalar Uyuşmuyor!");
        getContentPane().add(lbUyarı, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 146, 20));

        jLabel14.setText("*");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 152, 5, -1));

        jLabel5.setText("Telefon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 189, -1, -1));

        jLabel15.setText("*");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 98, 5, -1));

        jLabel6.setText("E-Posta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 233, -1, 24));

        jLabel16.setText("*");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, 20));

        jLabel17.setText("*");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 189, 5, -1));

        jLabel18.setText("*");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 237, -1, -1));

        jLabel8.setText("Soyadınız");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 143, -1, -1));

        jLabel7.setText("Şifre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 74, 20));

        jLabel19.setText("*");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, 20));

        jLabel10.setText("E-Posta Tekrar");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, 20));

        lbSifre.setText("Şifreler Uyuşmuyor!");
        getContentPane().add(lbSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 136, 20));

        jLabel2.setText("Ad kısmı boş bırakılamaz.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 94, 146, 24));

        jLabel4.setText("Soyad kısmı boş bırakılamaz.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 140, -1, 28));

        jLabel13.setText("Telefon kısmı boş bırakılamaz.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 186, -1, 29));

        jLabel9.setText("Adres Bilgileriniz");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, -1));

        jComboMüsteriİl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İl Seçiniz", "İstanbul Anadolu", "İstanbul Avrupa" }));
        jComboMüsteriİl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMüsteriİlActionPerformed(evt);
            }
        });
        getContentPane().add(jComboMüsteriİl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        jComboMüsteri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboMüsteri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboMüsteriMousePressed(evt);
            }
        });
        jComboMüsteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMüsteriActionPerformed(evt);
            }
        });
        getContentPane().add(jComboMüsteri, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, 110, -1));

        jLabel21.setText("Adres İli");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 70, 20));

        jLabel22.setText("Adres İlçesi");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, -1, 20));

        jTextField1.setText("Mahalle,Cadde,Sokak,No/Daire");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 220, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void txtAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdiActionPerformed

    }//GEN-LAST:event_txtAdiActionPerformed

    private void txtAdiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdiKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < 'A') || (caracter > 'z')) && (caracter != '\b')) {

            evt.consume();
        }

    }//GEN-LAST:event_txtAdiKeyTyped

    private void txtTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonActionPerformed

    }//GEN-LAST:event_txtTelefonActionPerformed

    private void txtTelefonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b')) {

            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonKeyTyped
    int müsteriID = 130;
    int a;
    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        if (!desenKontrol("[A-Za-z0-9]+[@][A-Za-z0-9]+(.com)", txtEmail.getText())) {
            lb1Email.setVisible(true);
        } else {
            lb1Email.setVisible(false);
        }
    }//GEN-LAST:event_txtEmailActionPerformed
    static ArrayList<Gonderici> göndericiler = new ArrayList();
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_Proje_Odevi_HalilIbrahimPU");
   
    private void btnKaydolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydolActionPerformed
        eposta(txtEmail.getText());
        if (!desenKontrol("[A-Za-z0-9]+[@][A-Za-z0-9]+(.com)", txtEmail.getText())) {
            lb1Email.setVisible(true);
        } else {
            lb1Email.setVisible(false);
        }
        if (!txtTekrar.getText().equals(txtEmail.getText())) {
            lbUyarı.setVisible(true);
        } else {
            lbUyarı.setVisible(false);
        }
        if (!txtŞifre.getText().equals(txtŞifTek.getText())) {
            lbSifre.setVisible(true);
        }
        if (txtAdi.getText().isEmpty() || txtSoyadı.getText().isEmpty() || txtTelefon.getText().isEmpty() || txtEmail.getText().isEmpty() || txtTekrar.getText().isEmpty() || txtŞifre.getText().isEmpty() || txtŞifTek.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "* ile işaretlenmiş alanlar boş bırakılamaz", "Uyarı", JOptionPane.WARNING_MESSAGE);
        } 
        
        else {

            EntityManager em = emf.createEntityManager();
            Müsteri newMüsteri = new Müsteri();
            newMüsteri.setMId(müsteriID+1);
            newMüsteri.setMAdi(txtAdi.getText());
            newMüsteri.setMSoyadi(txtSoyadı.getText());
            newMüsteri.setMTelefon((int)Integer.parseInt(txtTelefon.getText()));
            newMüsteri.setMSiFre(txtŞifTek.getText());
            newMüsteri.setEposta(txtEmail.getText());
            newMüsteri.setAdresiL(jComboMüsteriİl.getSelectedItem().toString());
            newMüsteri.setAdresiLçe(jComboMüsteri.getSelectedItem().toString());
            newMüsteri.setAdres(jTextField1.getText());
            müsteriID = newMüsteri.getMId();

            em.getTransaction().begin();
            em.persist(newMüsteri);
            em.getTransaction().commit();

        }
        
       

    }//GEN-LAST:event_btnKaydolActionPerformed

    private void txtSoyadıKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoyadıKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < 'A') || (caracter > 'z')) && (caracter != '\b')) {

            evt.consume();
        }
    }//GEN-LAST:event_txtSoyadıKeyTyped

    private void txtTekrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTekrarActionPerformed

    }//GEN-LAST:event_txtTekrarActionPerformed

    private void txtŞifreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtŞifreMouseClicked
        txtŞifre.setText(null);
    }//GEN-LAST:event_txtŞifreMouseClicked

    private void txtŞifTekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtŞifTekActionPerformed

    }//GEN-LAST:event_txtŞifTekActionPerformed

    private void txtŞifTekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtŞifTekMouseClicked
        txtŞifTek.setText(null);
    }//GEN-LAST:event_txtŞifTekMouseClicked

    private void jComboMüsteriİlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMüsteriİlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboMüsteriİlActionPerformed

    private void jComboMüsteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMüsteriActionPerformed
       
    }//GEN-LAST:event_jComboMüsteriActionPerformed

    private void jComboMüsteriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboMüsteriMousePressed
        String[] ilçelerdizi = {"Ataşehir", "Beykoz", "Çekmeköy", "Kadıköy", "Kartal", "Maltepe", "Pendik", "Sancaktepe", "Sultanbeyli", "Şile", "Tuzla", "Ümraniye", "Üsküdar"};
        String[] ilçeler2dizi = {"Arnavutköy", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş ", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca ", "Esenler", "Esenyurt", "Eyüp ", "Fatih", "Gaziosmanpaşa", "Güngören", "Kağıthane", "Küçükçekmece", "Sarıyer", "Silivri", "Sultangazi", "Şişli", "Zeytinburnu"};
        DefaultComboBoxModel ilçelermodel1 = new DefaultComboBoxModel(ilçelerdizi);
        DefaultComboBoxModel ilçelermodel2 = new DefaultComboBoxModel(ilçeler2dizi);
        String il;
        
        il = jComboMüsteriİl.getSelectedItem().toString();
        for (int i = 0; i < 2; i++) {
            
            if (il.equals("İstanbul Anadolu")) {
                jComboMüsteri.setModel(ilçelermodel1);
            }break;
        }
        if (il.equals("İstanbul Avrupa")) {
           jComboMüsteri.setModel(ilçelermodel2);
        }
    }//GEN-LAST:event_jComboMüsteriMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kaydol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kaydol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kaydol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kaydol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kaydol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydol;
    private javax.swing.JComboBox<String> jComboMüsteri;
    private javax.swing.JComboBox<String> jComboMüsteriİl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb1Email;
    private javax.swing.JLabel lbSifre;
    private javax.swing.JLabel lbUyarı;
    private javax.swing.JTextField txtAdi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSoyadı;
    private javax.swing.JTextField txtTekrar;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JPasswordField txtŞifTek;
    private javax.swing.JPasswordField txtŞifre;
    // End of variables declaration//GEN-END:variables
}
