/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_proje_ödevi_halilibrahim;

import static bp2_proje_ödevi_halilibrahim.SubedekiKargolar.dtm1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author halil
 */
public class ŞubeAnaSayfa extends javax.swing.JFrame {

    /**
     * Creates new form ŞubeAnaSayfa
     */
    static ArrayList<Paket> subedekiPaketler = new ArrayList();
    AnaEkran AnaEkran = new AnaEkran(subedekiPaketler);
    DefaultListModel dlm = new DefaultListModel();
    DefaultListModel dlm1 = new DefaultListModel();

    public ŞubeAnaSayfa() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        KargoEkle KargoEkle = new KargoEkle(subedekiPaketler);
        jList1.setModel(dlm);
        try {
            //veri gönderme
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/KargoTakip", "sa", "as");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM KURYE ");
            while (rs.next()) {
                dlm.addElement(rs.getString(1));

            }

        } catch (SQLException ex) {
            Logger.getLogger(KuryeCagir.class.getName()).log(Level.SEVERE, null, ex);
        }
        jList2.setModel(dlm1);
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_Proje_Odevi_HalilIbrahimPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("select k from Kargo k Where k.gönderidurumu=:kd");
        q.setParameter("kd", "Subede");
        List<Kargo> kargolar = q.getResultList();

        for (Kargo k : kargolar) {

            dlm1.addElement(k.getKargoid());

        }
    }
    ArrayList göndericilerYeni;

    public ŞubeAnaSayfa(ArrayList a) {
        initComponents();
        göndericilerYeni = a;
    }

    void gelenlerVeriler(List id) {
        dlm.addElement(id);
    }
    SubedekiKargolar SubedekiKargolar = new SubedekiKargolar(subedekiPaketler);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnTeslimAl = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        btnAracaTeslimEt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 140, 170));

        jLabel2.setText("Kurye ile gelen kargolar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 140, 30));

        btnTeslimAl.setText("Şubeye Kabul Et");
        btnTeslimAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeslimAlActionPerformed(evt);
            }
        });
        getContentPane().add(btnTeslimAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 150, 170));

        jLabel3.setText("Araca Teslim Edilecek Kargolar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        btnAracaTeslimEt.setText("Araca Teslim Et");
        btnAracaTeslimEt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAracaTeslimEtActionPerformed(evt);
            }
        });
        getContentPane().add(btnAracaTeslimEt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jMenu2.setText("Şube İşlemleri");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        jMenuItem3.setText("Şube Stok Bilgileri");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Kargo Hazırla");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        KargoEkle KargoEkle = new KargoEkle(subedekiPaketler);
        KargoEkle.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    Paket p = new Paket();
    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked

    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SubedekiKargolar subedekiKargolar = new SubedekiKargolar();
        subedekiKargolar.setVisible(true);
        subedekiKargolar.pack();
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    Kargo newKargo = new Kargo();
    Kurye newKurye = new Kurye();
    Müsteri newMüsteri = new Müsteri();
    private void btnTeslimAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeslimAlActionPerformed
        try {

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_Proje_Odevi_HalilIbrahimPU");
            EntityManager em = emf.createEntityManager();
            Query q = em.createQuery("select k FROM Kurye k Where k.paketId=:pid");//"UPDATE Kurye k SET k.kargodurum Where k.paketId=:pid "
            q.setParameter("pid", jList1.getSelectedValue());
            List<Kurye> kuryedekiler = q.getResultList();
            for (Kurye kurye : kuryedekiler) {
                Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/KargoTakip", "sa", "as");
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("SELECT * FROM MÜSTERİ");
                ResultSet rs1 = stmt.executeQuery("SELECT * FROM KURYE");
                newKargo.setAdres(kurye.getAliciadres());
                newKargo.setAdresiLi(kurye.getAliciiL());
                newKargo.setAdresiLçesi(kurye.getAliciiLçe());
                newKargo.setAliciadi(kurye.getAliciad());
                newKargo.setGönderidurumu("Subede");
                newKargo.setTariH(kurye.getTariH());
                newKargo.setTeslimatucreti(0);
                newKargo.setGönderiCiId(Integer.parseInt(kurye.getGönderiCiId()));
                newKargo.setKargoid(14);
                newKargo.setGönderitipi(kurye.getPakettiPi());
                newKargo.setÖdemetipi("");

            }
            em.getTransaction().begin();
            em.persist(newKargo);
            em.getTransaction().commit();

        } catch (SQLException ex) {
            Logger.getLogger(ŞubeAnaSayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btnTeslimAlActionPerformed

    private void btnAracaTeslimEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAracaTeslimEtActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("BP2_Proje_Odevi_HalilIbrahimPU");
        EntityManager em = emf.createEntityManager();
        Query q = em.createQuery("UPDATE Kargo k SET k.gönderidurumu=:durum Where k.kargoid=:kid ");
        q.setParameter("kid", (jList2.getSelectedValue()));
        q.setParameter("durum", "Araca teslim edildi");
        em.getTransaction().begin();
        q.executeUpdate();
        em.getTransaction().commit();
        em.close();
    }//GEN-LAST:event_btnAracaTeslimEtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ŞubeAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ŞubeAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ŞubeAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ŞubeAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ŞubeAnaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAracaTeslimEt;
    private javax.swing.JButton btnTeslimAl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
